import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";

// Initializes Inter font with selected subsets for global usage
const inter = Inter({ subsets: ["latin"] });
import { Toaster } from "@/components/ui/toaster"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <head>
          <meta name="viewport" content="width=device-width, initial-scale=1.0" />
          <title>TeachMate</title>
        </head>

      <body className={inter.className}>
        <Navbar/>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
